# coding: utf-8

"""
    API para Programação Diária de Produção (PDP).

    API do PDP para obtenção de dados e informações sobre programação diária de produção.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.usina_api import UsinaApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsinaApi(unittest.TestCase):
    """UsinaApi unit test stubs"""

    def setUp(self):
        self.api = UsinaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_insumo_pdp_listar_geracao_proposta(self):
        """Test case for insumo_pdp_listar_geracao_proposta

        Listar a geração proposta por Usina em base semi-horária.  # noqa: E501
        """
        pass

    def test_insumo_pdp_listar_geracao_proposta_get(self):
        """Test case for insumo_pdp_listar_geracao_proposta_get

        Listar a geração proposta por Usina em base semi-horária.  # noqa: E501
        """
        pass

    def test_insumo_pdp_listar_usinas_representadas(self):
        """Test case for insumo_pdp_listar_usinas_representadas

        Listar Usinas representadas pelo usuário.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
