# coding: utf-8

"""
    API para Programação Diária de Produção (PDP).

    API do PDP para obtenção de dados e informações sobre programação diária de produção.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.balanco_programado_api import BalancoProgramadoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBalancoProgramadoApi(unittest.TestCase):
    """BalancoProgramadoApi unit test stubs"""

    def setUp(self):
        self.api = BalancoProgramadoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_balanco_programado_listar_carga_medio_diaria(self):
        """Test case for balanco_programado_listar_carga_medio_diaria

        Listar a carga do balanço programado de energia médio diário (MWMED) por Região  # noqa: E501
        """
        pass

    def test_balanco_programado_listar_geracao_medio_diaria(self):
        """Test case for balanco_programado_listar_geracao_medio_diaria

        Listar a geração do balanço programado de energia médio diário (MWMED) por Região  # noqa: E501
        """
        pass

    def test_balanco_programado_listar_intercambio_liquido_medio_diaria(self):
        """Test case for balanco_programado_listar_intercambio_liquido_medio_diaria

        Listar o intercâmbio liquido programado por Região  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
