# coding: utf-8

"""
    API para Programação Diária de Produção (PDP).

    API do PDP para obtenção de dados e informações sobre programação diária de produção.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.empresa_api import EmpresaApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEmpresaApi(unittest.TestCase):
    """EmpresaApi unit test stubs"""

    def setUp(self):
        self.api = EmpresaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_empresa_listar_empresas_representadas(self):
        """Test case for empresa_listar_empresas_representadas

        Listar dados das Empresas representadas pelo usuário  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
