# coding: utf-8

"""
    API para Programação Diária de Produção (PDP).

    API do PDP para obtenção de dados e informações sobre programação diária de produção.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_balanco_carga_response_balanco import AllOfBalancoCargaResponseBalanco  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfBalancoCargaResponseBalanco(unittest.TestCase):
    """AllOfBalancoCargaResponseBalanco unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfBalancoCargaResponseBalanco(self):
        """Test AllOfBalancoCargaResponseBalanco"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_balanco_carga_response_balanco.AllOfBalancoCargaResponseBalanco()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
