# coding: utf-8

"""
    Integração com o SGI-OP

    Api de integração com os dados dos SGI-OP.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.mensagem_erro_dto import MensagemErroDto  # noqa: E501
from swagger_client.rest import ApiException


class TestMensagemErroDto(unittest.TestCase):
    """MensagemErroDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMensagemErroDto(self):
        """Test MensagemErroDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.mensagem_erro_dto.MensagemErroDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
