# coding: utf-8

"""
    Integração com o SGI-OP

    Api de integração com os dados dos SGI-OP.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.historico_dto import HistoricoDto  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoricoDto(unittest.TestCase):
    """HistoricoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoricoDto(self):
        """Test HistoricoDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.historico_dto.HistoricoDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
