# coding: utf-8

"""
    Integração com o SGI-OP

    Api de integração com os dados dos SGI-OP.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.dominio_dto import DominioDto  # noqa: E501
from swagger_client.rest import ApiException


class TestDominioDto(unittest.TestCase):
    """DominioDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDominioDto(self):
        """Test DominioDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dominio_dto.DominioDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
