# coding: utf-8

"""
    Integração com o SGI-OP

    Api de integração com os dados dos SGI-OP.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resultado_historico_dados_execucao_intervencao_dto import ResultadoHistoricoDadosExecucaoIntervencaoDto  # noqa: E501
from swagger_client.rest import ApiException


class TestResultadoHistoricoDadosExecucaoIntervencaoDto(unittest.TestCase):
    """ResultadoHistoricoDadosExecucaoIntervencaoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResultadoHistoricoDadosExecucaoIntervencaoDto(self):
        """Test ResultadoHistoricoDadosExecucaoIntervencaoDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resultado_historico_dados_execucao_intervencao_dto.ResultadoHistoricoDadosExecucaoIntervencaoDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
