# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Erro(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tipo': 'str',
        'mensagens': 'list[ErroMensagens]'
    }

    attribute_map = {
        'tipo': 'Tipo',
        'mensagens': 'Mensagens'
    }

    def __init__(self, tipo=None, mensagens=None):  # noqa: E501
        """Erro - a model defined in Swagger"""  # noqa: E501
        self._tipo = None
        self._mensagens = None
        self.discriminator = None
        if tipo is not None:
            self.tipo = tipo
        if mensagens is not None:
            self.mensagens = mensagens

    @property
    def tipo(self):
        """Gets the tipo of this Erro.  # noqa: E501

        Tipo do Erro  # noqa: E501

        :return: The tipo of this Erro.  # noqa: E501
        :rtype: str
        """
        return self._tipo

    @tipo.setter
    def tipo(self, tipo):
        """Sets the tipo of this Erro.

        Tipo do Erro  # noqa: E501

        :param tipo: The tipo of this Erro.  # noqa: E501
        :type: str
        """

        self._tipo = tipo

    @property
    def mensagens(self):
        """Gets the mensagens of this Erro.  # noqa: E501


        :return: The mensagens of this Erro.  # noqa: E501
        :rtype: list[ErroMensagens]
        """
        return self._mensagens

    @mensagens.setter
    def mensagens(self, mensagens):
        """Sets the mensagens of this Erro.


        :param mensagens: The mensagens of this Erro.  # noqa: E501
        :type: list[ErroMensagens]
        """

        self._mensagens = mensagens

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Erro, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Erro):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
