# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.paginacao import Paginacao  # noqa: F401,E501

class ResultadoConsultaGrandezaPaginada(Paginacao):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reservatorio': 'Reservatorio',
        'resultados': 'list[Resultado]'
    }
    if hasattr(Paginacao, "swagger_types"):
        swagger_types.update(Paginacao.swagger_types)

    attribute_map = {
        'reservatorio': 'Reservatorio',
        'resultados': 'Resultados'
    }
    if hasattr(Paginacao, "attribute_map"):
        attribute_map.update(Paginacao.attribute_map)

    def __init__(self, reservatorio=None, resultados=None, *args, **kwargs):  # noqa: E501
        """ResultadoConsultaGrandezaPaginada - a model defined in Swagger"""  # noqa: E501
        self._reservatorio = None
        self._resultados = None
        self.discriminator = None
        if reservatorio is not None:
            self.reservatorio = reservatorio
        if resultados is not None:
            self.resultados = resultados
        Paginacao.__init__(self, *args, **kwargs)

    @property
    def reservatorio(self):
        """Gets the reservatorio of this ResultadoConsultaGrandezaPaginada.  # noqa: E501


        :return: The reservatorio of this ResultadoConsultaGrandezaPaginada.  # noqa: E501
        :rtype: Reservatorio
        """
        return self._reservatorio

    @reservatorio.setter
    def reservatorio(self, reservatorio):
        """Sets the reservatorio of this ResultadoConsultaGrandezaPaginada.


        :param reservatorio: The reservatorio of this ResultadoConsultaGrandezaPaginada.  # noqa: E501
        :type: Reservatorio
        """

        self._reservatorio = reservatorio

    @property
    def resultados(self):
        """Gets the resultados of this ResultadoConsultaGrandezaPaginada.  # noqa: E501


        :return: The resultados of this ResultadoConsultaGrandezaPaginada.  # noqa: E501
        :rtype: list[Resultado]
        """
        return self._resultados

    @resultados.setter
    def resultados(self, resultados):
        """Sets the resultados of this ResultadoConsultaGrandezaPaginada.


        :param resultados: The resultados of this ResultadoConsultaGrandezaPaginada.  # noqa: E501
        :type: list[Resultado]
        """

        self._resultados = resultados

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResultadoConsultaGrandezaPaginada, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResultadoConsultaGrandezaPaginada):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
