# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Resultado(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instante': 'datetime',
        'valor': 'float'
    }

    attribute_map = {
        'instante': 'Instante',
        'valor': 'Valor'
    }

    def __init__(self, instante=None, valor=None):  # noqa: E501
        """Resultado - a model defined in Swagger"""  # noqa: E501
        self._instante = None
        self._valor = None
        self.discriminator = None
        if instante is not None:
            self.instante = instante
        if valor is not None:
            self.valor = valor

    @property
    def instante(self):
        """Gets the instante of this Resultado.  # noqa: E501

        Instante da medida  # noqa: E501

        :return: The instante of this Resultado.  # noqa: E501
        :rtype: datetime
        """
        return self._instante

    @instante.setter
    def instante(self, instante):
        """Sets the instante of this Resultado.

        Instante da medida  # noqa: E501

        :param instante: The instante of this Resultado.  # noqa: E501
        :type: datetime
        """

        self._instante = instante

    @property
    def valor(self):
        """Gets the valor of this Resultado.  # noqa: E501

        Valor da medida  # noqa: E501

        :return: The valor of this Resultado.  # noqa: E501
        :rtype: float
        """
        return self._valor

    @valor.setter
    def valor(self, valor):
        """Sets the valor of this Resultado.

        Valor da medida  # noqa: E501

        :param valor: The valor of this Resultado.  # noqa: E501
        :type: float
        """

        self._valor = valor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Resultado, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Resultado):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
