# coding: utf-8

# flake8: noqa

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.autenticao_api import AutenticaoApi
from swagger_client.api.grandezas_hidrolgicas_api import GrandezasHidrolgicasApi
from swagger_client.api.grandezas_previstas_api import GrandezasPrevistasApi
from swagger_client.api.grandezas_verificadas_api import GrandezasVerificadasApi
from swagger_client.api.precipitao_observada_api import PrecipitaoObservadaApi
from swagger_client.api.reservatrio_api import ReservatrioApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.autenticacao import Autenticacao
from swagger_client.models.erro import Erro
from swagger_client.models.erro_mensagens import ErroMensagens
from swagger_client.models.grandeza_hidrologica import GrandezaHidrologica
from swagger_client.models.grandezas_hidrologicas_result import GrandezasHidrologicasResult
from swagger_client.models.paginacao import Paginacao
from swagger_client.models.precipacao_observada_result import PrecipacaoObservadaResult
from swagger_client.models.precipitacao import Precipitacao
from swagger_client.models.previsao_reservatorio import PrevisaoReservatorio
from swagger_client.models.renovar_autenticaco import RenovarAutenticaco
from swagger_client.models.reservatorio import Reservatorio
from swagger_client.models.resultado import Resultado
from swagger_client.models.resultado_autenticacao import ResultadoAutenticacao
from swagger_client.models.resultado_consulta_grandeza_paginada import ResultadoConsultaGrandezaPaginada
from swagger_client.models.resultado_consulta_reservatorios_paginada import ResultadoConsultaReservatoriosPaginada
from swagger_client.models.resultado_erro_padrao import ResultadoErroPadrao
from swagger_client.models.resultado_previsao_reservatorio import ResultadoPrevisaoReservatorio
