# coding: utf-8

# flake8: noqa

"""
    Integração com o SGI-OP

    Api de integração com os dados dos SGI-OP.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.autenticacao_api import AutenticacaoApi
from swagger_client.api.intervencao_controller_api import IntervencaoControllerApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.autenticar import Autenticar
from swagger_client.models.dados_execucao_dto import DadosExecucaoDto
from swagger_client.models.dominio_dto import DominioDto
from swagger_client.models.equipamento_intervencao_dto import EquipamentoIntervencaoDto
from swagger_client.models.erro_autenticacao import ErroAutenticacao
from swagger_client.models.error import Error
from swagger_client.models.historico_dto import HistoricoDto
from swagger_client.models.intervencao_dto import IntervencaoDto
from swagger_client.models.intervencoes_importarlote_body import IntervencoesImportarloteBody
from swagger_client.models.mensagem_erro_dto import MensagemErroDto
from swagger_client.models.renovar import Renovar
from swagger_client.models.resposta_consulta_dominios_dto import RespostaConsultaDominiosDto
from swagger_client.models.resposta_consulta_intervencao_dto import RespostaConsultaIntervencaoDto
from swagger_client.models.resposta_consulta_situacao_importacao_lote_dto import RespostaConsultaSituacaoImportacaoLoteDto
from swagger_client.models.resposta_erro_padrao_dto import RespostaErroPadraoDto
from swagger_client.models.resposta_upload_intervencoes_dto import RespostaUploadIntervencoesDto
from swagger_client.models.resultado_autenticacao import ResultadoAutenticacao
from swagger_client.models.resultado_historico_dados_execucao_intervencao_dto import ResultadoHistoricoDadosExecucaoIntervencaoDto
