# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.grandeza_hidrologica import GrandezaHidrologica  # noqa: E501
from swagger_client.rest import ApiException


class TestGrandezaHidrologica(unittest.TestCase):
    """GrandezaHidrologica unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrandezaHidrologica(self):
        """Test GrandezaHidrologica"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.grandeza_hidrologica.GrandezaHidrologica()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
