# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.autenticao_api import AutenticaoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAutenticaoApi(unittest.TestCase):
    """AutenticaoApi unit test stubs"""

    def setUp(self):
        self.api = AutenticaoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_autenticar(self):
        """Test case for post_autenticar

        """
        pass

    def test_post_renovar(self):
        """Test case for post_renovar

        """
        pass


if __name__ == '__main__':
    unittest.main()
