# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.precipitao_observada_api import PrecipitaoObservadaApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPrecipitaoObservadaApi(unittest.TestCase):
    """PrecipitaoObservadaApi unit test stubs"""

    def setUp(self):
        self.api = PrecipitaoObservadaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_precipitacao_observada(self):
        """Test case for get_precipitacao_observada

        """
        pass


if __name__ == '__main__':
    unittest.main()
