# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.grandezas_previstas_api import GrandezasPrevistasApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGrandezasPrevistasApi(unittest.TestCase):
    """GrandezasPrevistasApi unit test stubs"""

    def setUp(self):
        self.api = GrandezasPrevistasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_consultar_previsoes(self):
        """Test case for consultar_previsoes

        Realiza a consulta das previsões das vazões diárias por reservatório.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
