# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reservatrio_api import ReservatrioApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReservatrioApi(unittest.TestCase):
    """ReservatrioApi unit test stubs"""

    def setUp(self):
        self.api = ReservatrioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_reservatorios(self):
        """Test case for get_reservatorios

        """
        pass

    def test_get_reservatorios_by_id(self):
        """Test case for get_reservatorios_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
