# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.autenticacao import Autenticacao  # noqa: E501
from swagger_client.rest import ApiException


class TestAutenticacao(unittest.TestCase):
    """Autenticacao unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutenticacao(self):
        """Test Autenticacao"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.autenticacao.Autenticacao()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
