# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.grandezas_hidrolgicas_api import GrandezasHidrolgicasApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGrandezasHidrolgicasApi(unittest.TestCase):
    """GrandezasHidrolgicasApi unit test stubs"""

    def setUp(self):
        self.api = GrandezasHidrolgicasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_grandezas_hidrologicas(self):
        """Test case for get_grandezas_hidrologicas

        """
        pass


if __name__ == '__main__':
    unittest.main()
