# coding: utf-8

"""
    Hidrologia

    API que fornece dados hidrológicos  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.grandezas_verificadas_api import GrandezasVerificadasApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGrandezasVerificadasApi(unittest.TestCase):
    """GrandezasVerificadasApi unit test stubs"""

    def setUp(self):
        self.api = GrandezasVerificadasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_afluencia_reservatorio(self):
        """Test case for get_afluencia_reservatorio

        """
        pass

    def test_get_defluencia_reservatorio(self):
        """Test case for get_defluencia_reservatorio

        """
        pass

    def test_get_energia_turbinavel_reservatorio(self):
        """Test case for get_energia_turbinavel_reservatorio

        """
        pass

    def test_get_nivel_jusante_reservatorio(self):
        """Test case for get_nivel_jusante_reservatorio

        """
        pass

    def test_get_nivel_montante_reservatorio(self):
        """Test case for get_nivel_montante_reservatorio

        """
        pass

    def test_get_vazao_outras_estruturas_reservatorio(self):
        """Test case for get_vazao_outras_estruturas_reservatorio

        """
        pass

    def test_get_vazao_turbinada_reservatorio(self):
        """Test case for get_vazao_turbinada_reservatorio

        """
        pass

    def test_get_vazao_vertida_reservatorio(self):
        """Test case for get_vazao_vertida_reservatorio

        """
        pass

    def test_get_volume_util_reservatorio(self):
        """Test case for get_volume_util_reservatorio

        """
        pass


if __name__ == '__main__':
    unittest.main()
