# coding: utf-8

"""
    API Energia Agora

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sta-integracao-tec@ons.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.balano_energtico_consolidado_agora_api import BalanoEnergticoConsolidadoAgoraApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBalanoEnergticoConsolidadoAgoraApi(unittest.TestCase):
    """BalanoEnergticoConsolidadoAgoraApi unit test stubs"""

    def setUp(self):
        self.api = BalanoEnergticoConsolidadoAgoraApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_balanco_energetico_consolidado(self):
        """Test case for get_balanco_energetico_consolidado

        """
        pass


if __name__ == '__main__':
    unittest.main()
