# coding: utf-8

"""
    API Energia Agora

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sta-integracao-tec@ons.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.autenticacao_api import AutenticacaoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAutenticacaoApi(unittest.TestCase):
    """AutenticacaoApi unit test stubs"""

    def setUp(self):
        self.api = AutenticacaoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_autenticar(self):
        """Test case for post_autenticar

        """
        pass

    def test_post_renovar(self):
        """Test case for post_renovar

        """
        pass


if __name__ == '__main__':
    unittest.main()
