# coding: utf-8

"""
    API Energia Agora

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sta-integracao-tec@ons.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.gerao_por_fonte_minuto_a_minuto_hoje_api import GeraoPorFonteMinutoAMinutoHojeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGeraoPorFonteMinutoAMinutoHojeApi(unittest.TestCase):
    """GeraoPorFonteMinutoAMinutoHojeApi unit test stubs"""

    def setUp(self):
        self.api = GeraoPorFonteMinutoAMinutoHojeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_consultar_gearacai_mminuto(self):
        """Test case for get_consultar_gearacai_mminuto

        """
        pass


if __name__ == '__main__':
    unittest.main()
