# coding: utf-8

"""
    API Energia Agora

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sta-integracao-tec@ons.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.autenticar import Autenticar  # noqa: E501
from swagger_client.rest import ApiException


class TestAutenticar(unittest.TestCase):
    """Autenticar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutenticar(self):
        """Test Autenticar"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.autenticar.Autenticar()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
