# coding: utf-8

"""
    API Energia Agora

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sta-integracao-tec@ons.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.intercambio_internacional import IntercambioInternacional  # noqa: E501
from swagger_client.rest import ApiException


class TestIntercambioInternacional(unittest.TestCase):
    """IntercambioInternacional unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntercambioInternacional(self):
        """Test IntercambioInternacional"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.intercambio_internacional.IntercambioInternacional()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
