# coding: utf-8

"""
    API Energia Agora

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sta-integracao-tec@ons.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.situao_dos_reservatrios_agora_api import SituaoDosReservatriosAgoraApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSituaoDosReservatriosAgoraApi(unittest.TestCase):
    """SituaoDosReservatriosAgoraApi unit test stubs"""

    def setUp(self):
        self.api = SituaoDosReservatriosAgoraApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_situacao_dos_reservatorios(self):
        """Test case for situacao_dos_reservatorios

        """
        pass


if __name__ == '__main__':
    unittest.main()
