# coding: utf-8

"""
    API para Programação Diária de Produção (PDP).

    API do PDP para obtenção de dados e informações sobre programação diária de produção.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GeracaoPropostaRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ano': 'int',
        'mes': 'int',
        'dia': 'int',
        'codigos_usinas': 'list[str]'
    }

    attribute_map = {
        'ano': 'Ano',
        'mes': 'Mes',
        'dia': 'Dia',
        'codigos_usinas': 'CodigosUsinas'
    }

    def __init__(self, ano=None, mes=None, dia=None, codigos_usinas=None):  # noqa: E501
        """GeracaoPropostaRequest - a model defined in Swagger"""  # noqa: E501
        self._ano = None
        self._mes = None
        self._dia = None
        self._codigos_usinas = None
        self.discriminator = None
        self.ano = ano
        self.mes = mes
        self.dia = dia
        if codigos_usinas is not None:
            self.codigos_usinas = codigos_usinas

    @property
    def ano(self):
        """Gets the ano of this GeracaoPropostaRequest.  # noqa: E501

        (Obrigatório) Data do PDP (Ano).  # noqa: E501

        :return: The ano of this GeracaoPropostaRequest.  # noqa: E501
        :rtype: int
        """
        return self._ano

    @ano.setter
    def ano(self, ano):
        """Sets the ano of this GeracaoPropostaRequest.

        (Obrigatório) Data do PDP (Ano).  # noqa: E501

        :param ano: The ano of this GeracaoPropostaRequest.  # noqa: E501
        :type: int
        """
        if ano is None:
            raise ValueError("Invalid value for `ano`, must not be `None`")  # noqa: E501

        self._ano = ano

    @property
    def mes(self):
        """Gets the mes of this GeracaoPropostaRequest.  # noqa: E501

        (Obrigatório) Data do PDP (Mês).  # noqa: E501

        :return: The mes of this GeracaoPropostaRequest.  # noqa: E501
        :rtype: int
        """
        return self._mes

    @mes.setter
    def mes(self, mes):
        """Sets the mes of this GeracaoPropostaRequest.

        (Obrigatório) Data do PDP (Mês).  # noqa: E501

        :param mes: The mes of this GeracaoPropostaRequest.  # noqa: E501
        :type: int
        """
        if mes is None:
            raise ValueError("Invalid value for `mes`, must not be `None`")  # noqa: E501

        self._mes = mes

    @property
    def dia(self):
        """Gets the dia of this GeracaoPropostaRequest.  # noqa: E501

        (Obrigatório) Data do PDP (Dia).  # noqa: E501

        :return: The dia of this GeracaoPropostaRequest.  # noqa: E501
        :rtype: int
        """
        return self._dia

    @dia.setter
    def dia(self, dia):
        """Sets the dia of this GeracaoPropostaRequest.

        (Obrigatório) Data do PDP (Dia).  # noqa: E501

        :param dia: The dia of this GeracaoPropostaRequest.  # noqa: E501
        :type: int
        """
        if dia is None:
            raise ValueError("Invalid value for `dia`, must not be `None`")  # noqa: E501

        self._dia = dia

    @property
    def codigos_usinas(self):
        """Gets the codigos_usinas of this GeracaoPropostaRequest.  # noqa: E501

        (Opcional) Código das Usinas no PDP (Caso não informado retornará a geração de todos as usinas relacionadas ao usuário)  # noqa: E501

        :return: The codigos_usinas of this GeracaoPropostaRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._codigos_usinas

    @codigos_usinas.setter
    def codigos_usinas(self, codigos_usinas):
        """Sets the codigos_usinas of this GeracaoPropostaRequest.

        (Opcional) Código das Usinas no PDP (Caso não informado retornará a geração de todos as usinas relacionadas ao usuário)  # noqa: E501

        :param codigos_usinas: The codigos_usinas of this GeracaoPropostaRequest.  # noqa: E501
        :type: list[str]
        """

        self._codigos_usinas = codigos_usinas

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeracaoPropostaRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeracaoPropostaRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
